<?php
foreach ($CJWT['child_id'] as &$question) {
    if (trim($question['title']) === '一站式搬家打包如何收费？') {
        $question['content'] = '<p>志远半日式搬家280元/立方米、5立方米起，5立方米体积费用1400元；精品日式320元/立方米、10立方米起，10立方米体积费用3200元。两种均含旧家打包、包装材料、小家具拆装和装卸运输；精品增加新家还原。</p><p>已经自行打包，可选择380/469/569元普通车型套餐。例如469元套餐含10公里，行程15公里时，套餐加超里程费为469＋5×7＝504元；适用的楼层、拆装等增项另按确认报价计算。<a href="/pricing.html">查看收费明细</a></p>';
    }
}
unset($question);
?>
<section class="center boxsh pd20 mt25" style="line-height:1.9"><h2 class="fs-24">志远搬家报价说明</h2><p>居民搬家车型套餐380元、469元、569元，均含装车、运输、卸车；半日式280元/立方米、5立方米起，精品日式320元/立方米、10立方米起。吊装和工厂搬迁免费勘测后分项报价。</p><p><a href="/pricing.html">查看包含项目、额外费用与合同锁价承诺 →</a>　<a href="/detail/products15.html">查看日式搬家套餐 →</a></p></section>
<div class="center clearfix"><div class="wow fadeInUp"><div class="title-top clearfix mt45"><p><?= $BDTS['title'] ?> <span><?= $BDTS['subtitle'] ?></span></p></div><div class="characteristic mt20 boxsh clearfix"><ul><?php foreach ($BDTS['child_id'] as $item): ?><li><p class="img"><img class="lazy" data-original="<?= $item['image'] ?>" alt="<?= htmlspecialchars($item['title'], ENT_QUOTES, 'UTF-8') ?>" src="<?= $item['image'] ?>" style="display: block;"></p><p class="txt"><?= $item['title'] ?></p><div class="text-box"><p class="fs-18"><?= $item['title'] ?></p><p class="mt10 fs-14"><?= $item['sketch'] ?></p></div></li><?php endforeach; ?></ul></div></div></div>
<div class="center clearfix"><div class="wow fadeInUp" data-wow-delay="0.1s"><div class="title-top clearfix mt45"><p><?= $CJWT['title'] ?> <span><?= $CJWT['subtitle'] ?></span></p></div><div class="question-box mt20"><ul class="question-ul flex flex-wrap"><?php foreach ($CJWT['child_id'] as $item): ?><li><div class="question-li"><div class="fl"><span class="que-icon">Q</span></div><div class="fl question-title fs-16"><span><?= $item['title'] ?></span></div></div><div class="question-ans mt20"><div class="fl"><span class="ans-icon">A</span></div><div class="fl question-ans-text fs-14 c888 line-h-2"><?= html_entity_decode($item['content'] ?? '') ?></div></div></li><?php endforeach; ?></ul></div></div></div>
<div class="center clearfix"><div class="wow fadeInUp" data-wow-delay="0.1s"><div class="title-top clearfix mt45"><p><?= $why['title'] ?><span><?= $why['subtitle'] ?></span></p></div><div class="reasons pl-0 pr-0 mt20 boxsh over-hidden"><div class="left-content df js fc"><?php foreach (array_slice($why['child_id'], 0, 3) as $item): ?><div class="list list-left df ac"><div class="text text-right flex-1"><h3 class="fs-16 mb10"><?= $item['title'] ?></h3><p class="c888 fs-13 line-h-1-7"><?= $item['sketch'] ?></p></div><span class="ico fr"><img src="<?= $item['icon1'] ?>" class="icon_img icon1" alt=""><img src="<?= $item['icon2'] ?>" class="icon_img icon1_hover" alt=""></span></div><?php endforeach; ?></div><div class="center-content"><div class="top_video"><div class="img_box"><img src="<?= $why['image'] ?>" alt=""><span class="video_btn"></span><div class="img_c"></div></div><div class="hide"><video src="/upload/20260717/zhiyuan-service.mp4" width="100%" height="100%" controls preload="metadata"></video></div></div><div class="bottom_baojia"><img src="/static/home/images/r_img_01.png" alt=""><div class="mt25"><p class="fs-20 df ac">免费获取报价 <span class="hot">HOT</span></p><p class="mt10 mb10">30秒算一算搬家要花多少钱</p><p class="zixun-online getBaojia">立即获取</p></div></div></div><div class="right-content df js fc"><?php foreach (array_slice($why['child_id'], 3, 3) as $item): ?><div class="list list-right df ac"><span class="ico fr"><img src="<?= $item['icon1'] ?>" class="icon_img icon1" alt=""><img src="<?= $item['icon2'] ?>" class="icon_img icon1_hover" alt=""></span><div class="text text-left flex-1"><h3 class="fs-16 mb10"><?= $item['title'] ?></h3><p class="c888 fs-13 line-h-1-7"><?= $item['sketch'] ?></p></div></div><?php endforeach; ?></div></div></div></div>
<div class="center clearfix"><div class="wow fadeInUp" data-wow-delay="0.1s"><div class="title-top clearfix mt45"><p><?= $BZCL['title'] ?> <span><?= $BZCL['subtitle'] ?></span></p><p class="button-bz"><a href="javascript:" class="btn-left swiper-button-disabled" id="bz-btn-prev">‹</a><a href="javascript:" class="btn-right" id="bz-btn-next">›</a></p></div><div class="case-site mt20"><div class="swiper-container case-site-swiper swiper-container-horizontal"><div class="swiper-wrapper"><?php foreach ($BZCL['child_id'] as $item): ?><div class="swiper-slide swiper-slide-active"><div class="slide"><div class="img-box"><img class="lazy" data-original="<?= $item['image'] ?>" alt="<?= htmlspecialchars($item['title'], ENT_QUOTES, 'UTF-8') ?>" src="<?= $item['image'] ?>" style="display: block;"></div><div class="text-box"><p class="fs-16 mb10 text-center"><?= $item['title'] ?></p><p class="infos"><?= $item['sketch'] ?></p></div></div></div><?php endforeach; ?></div></div></div></div></div>

<section class="center boxsh pd20 mt25"><h2 class="fs-18">更多搬家问题</h2><p><a href="/faq.html">查看预约、打包、派工与售后常见问题 →</a></p></section>
