<?php
// Decode legacy fully entity-encoded bodies without double-decoding modern HTML.
$caseContent = (string)($detail['content'] ?? '');
if (strpos($caseContent, '<') === false) {
    $caseContent = html_entity_decode($caseContent, ENT_QUOTES, 'UTF-8');
}
?>
<?php include VIEW_PATH . 'layout/header.php'; ?>
<link rel="stylesheet" href="<?= htmlspecialchars($assetUrl('/static/home/css/news.css'), ENT_QUOTES, 'UTF-8') ?>">
<link rel="stylesheet" href="<?= htmlspecialchars($assetUrl('/static/home/css/case-article.css'), ENT_QUOTES, 'UTF-8') ?>">
<div class="page-banner"><img src="<?= htmlspecialchars($assetUrl($banner), ENT_QUOTES, 'UTF-8') ?>" class="w100 block" alt=""></div>
<div><div class="column-menu center boxsh pd20 mt25 wow fadeInUp" data-wow-delay="0.1s"><div class="border-bottom"><div class="column-menu-list clearfix"><p><a>资讯类型：</a></p><p class="clearfix column-menu-list-nav"><?php foreach ($classify as $item): ?><a href="<?= $item['href'] ?: '/cases/' . $item['id'] . '.html' ?>" target="<?= $item['target'] ?: '_self' ?>"><?= $item['title'] ?></a><?php endforeach; ?></p></div></div></div></div>
<div><div class="case-container center mt25 clearfix position-relative"><div class="left"><div class="news-article boxsh wow fadeInUp" data-wow-delay="0.1s"><div class="title mt10"><h1 class="fs-24"><?= htmlspecialchars($detail['headline'], ENT_QUOTES, 'UTF-8') ?></h1><p class="c888 mt10 fs-12"><span class="mr20">内容来源：志远搬家</span><span><?php if ($detail['display_time']): ?><?= $detail['time_label'] ?>：<?= date('Y-m-d H:i:s', $detail['display_time']) ?><?php endif; ?></span></p></div><section class="pd20" style="line-height:2"><h2 class="fs-18">案例信息卡</h2><ul><li>项目名称：<?= htmlspecialchars($detail['title'], ENT_QUOTES, 'UTF-8') ?></li><li>服务单位：广州志远搬家服务有限公司</li><li>案例分类：<?= htmlspecialchars($currentNav['title'] ?? '', ENT_QUOTES, 'UTF-8') ?></li><?php foreach ($detail['case_fields'] as $label => $value): ?><li><?= htmlspecialchars($label, ENT_QUOTES, 'UTF-8') ?>：<?= htmlspecialchars($value, ENT_QUOTES, 'UTF-8') ?></li><?php endforeach; ?></ul></section><p class="pd20" style="line-height:1.8"><?= htmlspecialchars($detail['summary'], ENT_QUOTES, 'UTF-8') ?></p><div class="article-box case-article-body mt25 fs-14 pb20"><?= $caseContent ?></div><div class="prev-next over-hidden border-top pt20 line-height-2"><div class="fl w40"><p class="fs-14 ellipsis c888"><?php if ($prev): ?>上一篇：<a href="/detail_cases<?= $prev['id'] ?>.html"><?= $prev['title'] ?></a><?php else: ?>上一篇：没有更多了<?php endif; ?></p></div><div class="fr w40 text-right"><p class="fs-14 ellipsis c888"><?php if ($next): ?>下一篇：<a href="/detail_cases<?= $next['id'] ?>.html"><?= $next['title'] ?></a><?php else: ?>下一篇：没有更多了<?php endif; ?></p></div></div></div><div class="recommend boxsh mt25 wow fadeInUp" data-wow-delay="0.1s"><div class="title clearfix"><h3 class="fl">相关资讯</h3></div><div class="recommend-read pd20 fs-14 line-height-2 over-hidden"><ul><?php foreach ($about_news as $item): ?><li class="ellipsis"><a href="<?= $item['link'] ?: '/detail_cases' . $item['id'] . '.html' ?>" target="<?= $item['target'] ?: '_self' ?>"><?= $item['title'] ?></a></li><?php endforeach; ?></ul></div></div></div><?php include VIEW_PATH . 'layout/news_right.php'; ?></div></div>
<script src="<?= htmlspecialchars($assetUrl('/static/home/js/news.js'), ENT_QUOTES, 'UTF-8') ?>"></script>
<?php include VIEW_PATH . 'layout/footer.php'; ?>
