<?php include VIEW_PATH . 'layout/header.php'; ?>
<link rel="stylesheet" href="<?= htmlspecialchars($assetUrl('/static/home/css/news.css'), ENT_QUOTES, 'UTF-8') ?>">
<div class="page-banner"><img src="<?= htmlspecialchars($assetUrl($banner), ENT_QUOTES, 'UTF-8') ?>" class="w100 block" alt=""></div>
<section class="center boxsh pd20 mt25" style="line-height:1.9"><h1 class="fs-24">志远搬家服务案例</h1><h2 class="fs-18">案例覆盖总览</h2><p>本页按同城、跨市分类展示志远搬家的服务案例。点击项目查看案例图片、服务内容与项目介绍。</p><ul><?php foreach ($list as $case): ?><li><a href="/detail_cases<?= (int)$case['id'] ?>.html"><?= htmlspecialchars($case['title'], ENT_QUOTES, 'UTF-8') ?></a></li><?php endforeach; ?></ul></section>
<style>.column-menu-list-nav a[aria-current="page"]{color:#c6382c;font-weight:bold;border-bottom:2px solid #c6382c}</style>
<div><div class="column-menu center boxsh pd20 mt25 wow fadeInUp" data-wow-delay="0.1s"><div class="border-bottom"><div class="column-menu-list clearfix"><p><a>案例类型：</a></p><p class="clearfix column-menu-list-nav"><a href="/cases/6.html"<?= $selectedCaseNavId === 0 ? ' aria-current="page"' : '' ?>>全部案例</a><?php foreach ($classify as $item): ?><a href="<?= $item['href'] ?: '/cases/' . $item['id'] . '.html' ?>" target="<?= $item['target'] ?: '_self' ?>"<?= $selectedCaseNavId === (int)$item['id'] ? ' aria-current="page"' : '' ?>><?= $item['title'] ?></a><?php endforeach; ?></p></div></div></div></div>
<div><div class="case-container center mt25 clearfix position-relative"><div class="left"><div class="news-box fs-14"><?php if ($list): foreach ($list as $item): ?><div class="news-list pd20 boxsh clearfix mb25 wow fadeInUp" data-wow-delay="0.1s"><div class="news-left-img fl"><a href="<?= $item['link'] ?: '/detail_cases' . $item['id'] . '.html' ?>" target="<?= $item['target'] ?: '_self' ?>"><img class="lazy" data-original="<?= $item['image'] ?>" alt="<?= htmlspecialchars($item['title'] . '案例图片', ENT_QUOTES, 'UTF-8') ?>" width="230" height="162" src="<?= $item['image'] ?>" style="display: inline;"></a></div><div class="news-right-text fr"><h3 class="ellipsis"><a href="<?= $item['link'] ?: '/detail_cases' . $item['id'] . '.html' ?>" target="<?= $item['target'] ?: '_self' ?>"><?= $item['title'] ?></a></h3><p class="mt15 c888 line-h-1-7"><?= htmlspecialchars($item['summary'], ENT_QUOTES, 'UTF-8') ?></p><p class="over-hidden mt20"><span class="c888 fl"><?php if ($item['display_time']): ?><?= $item['time_label'] ?>：<?= date('Y-m-d H:i:s', $item['display_time']) ?><?php endif; ?></span><a href="<?= $item['link'] ?: '/detail_cases' . $item['id'] . '.html' ?>" target="<?= $item['target'] ?: '_self' ?>" class="danger-color fr">查看详情&gt;&gt;</a></p></div></div><?php endforeach; else: ?><i>没有更多了。。。。</i><?php endif; ?></div><?php if ($totalPage > 1): ?><div class="fenye pd20 boxsh mt25 wow fadeInUp" data-wow-delay="0.1s"><?php for ($i = 1; $i <= $totalPage; $i++): ?><li<?= $i === $page ? ' class="thisclass"' : '' ?>><a href="?page=<?= $i ?>"><?= $i ?></a></li><?php endfor; ?></div><?php endif; ?></div><?php include VIEW_PATH . 'layout/news_right.php'; ?></div></div>
<script src="<?= htmlspecialchars($assetUrl('/static/home/js/news.js'), ENT_QUOTES, 'UTF-8') ?>"></script>
<?php include VIEW_PATH . 'layout/footer.php'; ?>
